'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace PadsUpload
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="FileUploadStatus", [Namespace]:="https://www.private.dacs.dla.mil"),  _
     System.SerializableAttribute()>  _
    Partial Public Class FileUploadStatus
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private UploadStatusField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UploadErrorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UploadPathField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property UploadStatus() As Boolean
            Get
                Return Me.UploadStatusField
            End Get
            Set
                If (Me.UploadStatusField.Equals(value) <> true) Then
                    Me.UploadStatusField = value
                    Me.RaisePropertyChanged("UploadStatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property UploadError() As String
            Get
                Return Me.UploadErrorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UploadErrorField, value) <> true) Then
                    Me.UploadErrorField = value
                    Me.RaisePropertyChanged("UploadError")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property UploadPath() As String
            Get
                Return Me.UploadPathField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UploadPathField, value) <> true) Then
                    Me.UploadPathField = value
                    Me.RaisePropertyChanged("UploadPath")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="PadsRecord", [Namespace]:="https://www.private.dacs.dla.mil"),  _
     System.SerializableAttribute()>  _
    Partial Public Class PadsRecord
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private JobField As PadsUpload.PadsJob
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private JobLibField As PadsUpload.LibraryDetail
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private JobSvcField As PadsUpload.LibraryService
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private JobCategoryField As System.Collections.Generic.List(Of PadsUpload.Category)
        
        Private FolderIDField As Long
        
        Private DocumentIdField As Long
        
        Private DocVersionField As Long
        
        Private IsErrorField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastErrorField As String
        
        Private JobRoleField As Long
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Job() As PadsUpload.PadsJob
            Get
                Return Me.JobField
            End Get
            Set
                If (Object.ReferenceEquals(Me.JobField, value) <> true) Then
                    Me.JobField = value
                    Me.RaisePropertyChanged("Job")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property JobLib() As PadsUpload.LibraryDetail
            Get
                Return Me.JobLibField
            End Get
            Set
                If (Object.ReferenceEquals(Me.JobLibField, value) <> true) Then
                    Me.JobLibField = value
                    Me.RaisePropertyChanged("JobLib")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property JobSvc() As PadsUpload.LibraryService
            Get
                Return Me.JobSvcField
            End Get
            Set
                If (Object.ReferenceEquals(Me.JobSvcField, value) <> true) Then
                    Me.JobSvcField = value
                    Me.RaisePropertyChanged("JobSvc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property JobCategory() As System.Collections.Generic.List(Of PadsUpload.Category)
            Get
                Return Me.JobCategoryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.JobCategoryField, value) <> true) Then
                    Me.JobCategoryField = value
                    Me.RaisePropertyChanged("JobCategory")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property FolderID() As Long
            Get
                Return Me.FolderIDField
            End Get
            Set
                If (Me.FolderIDField.Equals(value) <> true) Then
                    Me.FolderIDField = value
                    Me.RaisePropertyChanged("FolderID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property DocumentId() As Long
            Get
                Return Me.DocumentIdField
            End Get
            Set
                If (Me.DocumentIdField.Equals(value) <> true) Then
                    Me.DocumentIdField = value
                    Me.RaisePropertyChanged("DocumentId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property DocVersion() As Long
            Get
                Return Me.DocVersionField
            End Get
            Set
                If (Me.DocVersionField.Equals(value) <> true) Then
                    Me.DocVersionField = value
                    Me.RaisePropertyChanged("DocVersion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=7)>  _
        Public Property IsError() As Boolean
            Get
                Return Me.IsErrorField
            End Get
            Set
                If (Me.IsErrorField.Equals(value) <> true) Then
                    Me.IsErrorField = value
                    Me.RaisePropertyChanged("IsError")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property LastError() As String
            Get
                Return Me.LastErrorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastErrorField, value) <> true) Then
                    Me.LastErrorField = value
                    Me.RaisePropertyChanged("LastError")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=9)>  _
        Public Property JobRole() As Long
            Get
                Return Me.JobRoleField
            End Get
            Set
                If (Me.JobRoleField.Equals(value) <> true) Then
                    Me.JobRoleField = value
                    Me.RaisePropertyChanged("JobRole")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="PadsJob", [Namespace]:="https://www.private.dacs.dla.mil"),  _
     System.SerializableAttribute()>  _
    Partial Public Class PadsJob
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private JobIdField As Long
        
        Private RoleIdField As Long
        
        Private StatusIdField As Long
        
        Private JobDtTmField As Date
        
        Private CSObjIdField As Long
        
        Private CsFolderIdField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CSPathField As String
        
        Private CsDocVerField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SrcDocPathField As String
        
        Private LibDetIdField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DestDocNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SrcSystemField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SrcReferenceField As String
        
        Private CatInheritFlagField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property JobId() As Long
            Get
                Return Me.JobIdField
            End Get
            Set
                If (Me.JobIdField.Equals(value) <> true) Then
                    Me.JobIdField = value
                    Me.RaisePropertyChanged("JobId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property RoleId() As Long
            Get
                Return Me.RoleIdField
            End Get
            Set
                If (Me.RoleIdField.Equals(value) <> true) Then
                    Me.RoleIdField = value
                    Me.RaisePropertyChanged("RoleId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property StatusId() As Long
            Get
                Return Me.StatusIdField
            End Get
            Set
                If (Me.StatusIdField.Equals(value) <> true) Then
                    Me.StatusIdField = value
                    Me.RaisePropertyChanged("StatusId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property JobDtTm() As Date
            Get
                Return Me.JobDtTmField
            End Get
            Set
                If (Me.JobDtTmField.Equals(value) <> true) Then
                    Me.JobDtTmField = value
                    Me.RaisePropertyChanged("JobDtTm")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property CSObjId() As Long
            Get
                Return Me.CSObjIdField
            End Get
            Set
                If (Me.CSObjIdField.Equals(value) <> true) Then
                    Me.CSObjIdField = value
                    Me.RaisePropertyChanged("CSObjId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property CsFolderId() As Long
            Get
                Return Me.CsFolderIdField
            End Get
            Set
                If (Me.CsFolderIdField.Equals(value) <> true) Then
                    Me.CsFolderIdField = value
                    Me.RaisePropertyChanged("CsFolderId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property CSPath() As String
            Get
                Return Me.CSPathField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CSPathField, value) <> true) Then
                    Me.CSPathField = value
                    Me.RaisePropertyChanged("CSPath")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=7)>  _
        Public Property CsDocVer() As Long
            Get
                Return Me.CsDocVerField
            End Get
            Set
                If (Me.CsDocVerField.Equals(value) <> true) Then
                    Me.CsDocVerField = value
                    Me.RaisePropertyChanged("CsDocVer")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property SrcDocPath() As String
            Get
                Return Me.SrcDocPathField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SrcDocPathField, value) <> true) Then
                    Me.SrcDocPathField = value
                    Me.RaisePropertyChanged("SrcDocPath")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=9)>  _
        Public Property LibDetId() As Long
            Get
                Return Me.LibDetIdField
            End Get
            Set
                If (Me.LibDetIdField.Equals(value) <> true) Then
                    Me.LibDetIdField = value
                    Me.RaisePropertyChanged("LibDetId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Property DestDocName() As String
            Get
                Return Me.DestDocNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DestDocNameField, value) <> true) Then
                    Me.DestDocNameField = value
                    Me.RaisePropertyChanged("DestDocName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public Property SrcSystem() As String
            Get
                Return Me.SrcSystemField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SrcSystemField, value) <> true) Then
                    Me.SrcSystemField = value
                    Me.RaisePropertyChanged("SrcSystem")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public Property SrcReference() As String
            Get
                Return Me.SrcReferenceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SrcReferenceField, value) <> true) Then
                    Me.SrcReferenceField = value
                    Me.RaisePropertyChanged("SrcReference")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=13)>  _
        Public Property CatInheritFlag() As Boolean
            Get
                Return Me.CatInheritFlagField
            End Get
            Set
                If (Me.CatInheritFlagField.Equals(value) <> true) Then
                    Me.CatInheritFlagField = value
                    Me.RaisePropertyChanged("CatInheritFlag")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LibraryDetail", [Namespace]:="https://www.private.dacs.dla.mil"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LibraryDetail
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private LibDetIdField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ShortNmField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LongNmField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SvcUsrField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SvcPassField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OnErrEmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OnErrCCField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property LibDetId() As Long
            Get
                Return Me.LibDetIdField
            End Get
            Set
                If (Me.LibDetIdField.Equals(value) <> true) Then
                    Me.LibDetIdField = value
                    Me.RaisePropertyChanged("LibDetId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ShortNm() As String
            Get
                Return Me.ShortNmField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ShortNmField, value) <> true) Then
                    Me.ShortNmField = value
                    Me.RaisePropertyChanged("ShortNm")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property LongNm() As String
            Get
                Return Me.LongNmField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LongNmField, value) <> true) Then
                    Me.LongNmField = value
                    Me.RaisePropertyChanged("LongNm")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property SvcUsr() As String
            Get
                Return Me.SvcUsrField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SvcUsrField, value) <> true) Then
                    Me.SvcUsrField = value
                    Me.RaisePropertyChanged("SvcUsr")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property SvcPass() As String
            Get
                Return Me.SvcPassField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SvcPassField, value) <> true) Then
                    Me.SvcPassField = value
                    Me.RaisePropertyChanged("SvcPass")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property OnErrEmail() As String
            Get
                Return Me.OnErrEmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OnErrEmailField, value) <> true) Then
                    Me.OnErrEmailField = value
                    Me.RaisePropertyChanged("OnErrEmail")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property OnErrCC() As String
            Get
                Return Me.OnErrCCField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OnErrCCField, value) <> true) Then
                    Me.OnErrCCField = value
                    Me.RaisePropertyChanged("OnErrCC")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LibraryService", [Namespace]:="https://www.private.dacs.dla.mil"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LibraryService
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private LibDetIdField As Long
        
        Private SeqNoField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SvcUrlField As String
        
        Private EnabledField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property LibDetId() As Long
            Get
                Return Me.LibDetIdField
            End Get
            Set
                If (Me.LibDetIdField.Equals(value) <> true) Then
                    Me.LibDetIdField = value
                    Me.RaisePropertyChanged("LibDetId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property SeqNo() As Long
            Get
                Return Me.SeqNoField
            End Get
            Set
                If (Me.SeqNoField.Equals(value) <> true) Then
                    Me.SeqNoField = value
                    Me.RaisePropertyChanged("SeqNo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SvcUrl() As String
            Get
                Return Me.SvcUrlField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SvcUrlField, value) <> true) Then
                    Me.SvcUrlField = value
                    Me.RaisePropertyChanged("SvcUrl")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property Enabled() As Boolean
            Get
                Return Me.EnabledField
            End Get
            Set
                If (Me.EnabledField.Equals(value) <> true) Then
                    Me.EnabledField = value
                    Me.RaisePropertyChanged("Enabled")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Category", [Namespace]:="https://www.private.dacs.dla.mil"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Category
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CategoryIDField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AttributesField As System.Collections.Generic.List(Of PadsUpload.Attribute)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property CategoryID() As Long
            Get
                Return Me.CategoryIDField
            End Get
            Set
                If (Me.CategoryIDField.Equals(value) <> true) Then
                    Me.CategoryIDField = value
                    Me.RaisePropertyChanged("CategoryID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Attributes() As System.Collections.Generic.List(Of PadsUpload.Attribute)
            Get
                Return Me.AttributesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AttributesField, value) <> true) Then
                    Me.AttributesField = value
                    Me.RaisePropertyChanged("Attributes")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Attribute", [Namespace]:="https://www.private.dacs.dla.mil"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Attribute
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AttributeNameField As String
        
        Private AttributeTypeField As PadsUpload.AttributeType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StringValueField As PadsUpload.ArrayOfString
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateValueField As PadsUpload.ArrayOfDateTime
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IntegerValueField As PadsUpload.ArrayOfLong
        
        Private BooleanValueField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SetValueField As System.Collections.Generic.List(Of System.Collections.Generic.List(Of PadsUpload.Attribute))
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property AttributeName() As String
            Get
                Return Me.AttributeNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AttributeNameField, value) <> true) Then
                    Me.AttributeNameField = value
                    Me.RaisePropertyChanged("AttributeName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property AttributeType() As PadsUpload.AttributeType
            Get
                Return Me.AttributeTypeField
            End Get
            Set
                If (Me.AttributeTypeField.Equals(value) <> true) Then
                    Me.AttributeTypeField = value
                    Me.RaisePropertyChanged("AttributeType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property StringValue() As PadsUpload.ArrayOfString
            Get
                Return Me.StringValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StringValueField, value) <> true) Then
                    Me.StringValueField = value
                    Me.RaisePropertyChanged("StringValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property DateValue() As PadsUpload.ArrayOfDateTime
            Get
                Return Me.DateValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DateValueField, value) <> true) Then
                    Me.DateValueField = value
                    Me.RaisePropertyChanged("DateValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property IntegerValue() As PadsUpload.ArrayOfLong
            Get
                Return Me.IntegerValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IntegerValueField, value) <> true) Then
                    Me.IntegerValueField = value
                    Me.RaisePropertyChanged("IntegerValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property BooleanValue() As Boolean
            Get
                Return Me.BooleanValueField
            End Get
            Set
                If (Me.BooleanValueField.Equals(value) <> true) Then
                    Me.BooleanValueField = value
                    Me.RaisePropertyChanged("BooleanValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property SetValue() As System.Collections.Generic.List(Of System.Collections.Generic.List(Of PadsUpload.Attribute))
            Get
                Return Me.SetValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SetValueField, value) <> true) Then
                    Me.SetValueField = value
                    Me.RaisePropertyChanged("SetValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AttributeType", [Namespace]:="https://www.private.dacs.dla.mil")>  _
    Public Enum AttributeType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DATEValue = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        STRINGValue = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        INTEGERValue = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        BOOLEANValue = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SETValue = 4
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfString", [Namespace]:="https://www.private.dacs.dla.mil", ItemName:="string"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfString
        Inherits System.Collections.Generic.List(Of String)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfDateTime", [Namespace]:="https://www.private.dacs.dla.mil", ItemName:="dateTime"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfDateTime
        Inherits System.Collections.Generic.List(Of Date)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfLong", [Namespace]:="https://www.private.dacs.dla.mil", ItemName:="long"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfLong
        Inherits System.Collections.Generic.List(Of Long)
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="https://www.private.dacs.dla.mil", ConfigurationName:="PadsUpload.PADSUploadSoap")>  _
    Public Interface PADSUploadSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.private.dacs.dla.mil/Online", ReplyAction:="*")>  _
        Function Online() As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.private.dacs.dla.mil/Online", ReplyAction:="*")>  _
        Function OnlineAsync() As System.Threading.Tasks.Task(Of Boolean)
        
        'CODEGEN: Generating message contract since element name Content from namespace https://www.private.dacs.dla.mil is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.private.dacs.dla.mil/UploadFile", ReplyAction:="*")>  _
        Function UploadFile(ByVal request As PadsUpload.UploadFileRequest) As PadsUpload.UploadFileResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.private.dacs.dla.mil/UploadFile", ReplyAction:="*")>  _
        Function UploadFileAsync(ByVal request As PadsUpload.UploadFileRequest) As System.Threading.Tasks.Task(Of PadsUpload.UploadFileResponse)
        
        'CODEGEN: Generating message contract since element name recordToAdd from namespace https://www.private.dacs.dla.mil is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.private.dacs.dla.mil/AddPadsJob", ReplyAction:="*")>  _
        Function AddPadsJob(ByVal request As PadsUpload.AddPadsJobRequest) As PadsUpload.AddPadsJobResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.private.dacs.dla.mil/AddPadsJob", ReplyAction:="*")>  _
        Function AddPadsJobAsync(ByVal request As PadsUpload.AddPadsJobRequest) As System.Threading.Tasks.Task(Of PadsUpload.AddPadsJobResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UploadFileRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UploadFile", [Namespace]:="https://www.private.dacs.dla.mil", Order:=0)>  _
        Public Body As PadsUpload.UploadFileRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PadsUpload.UploadFileRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.private.dacs.dla.mil")>  _
    Partial Public Class UploadFileRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Content() As Byte
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public FileName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public IsEncrypted As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Content() As Byte, ByVal FileName As String, ByVal IsEncrypted As Boolean)
            MyBase.New
            Me.Content = Content
            Me.FileName = FileName
            Me.IsEncrypted = IsEncrypted
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UploadFileResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UploadFileResponse", [Namespace]:="https://www.private.dacs.dla.mil", Order:=0)>  _
        Public Body As PadsUpload.UploadFileResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PadsUpload.UploadFileResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.private.dacs.dla.mil")>  _
    Partial Public Class UploadFileResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UploadFileResult As PadsUpload.FileUploadStatus
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UploadFileResult As PadsUpload.FileUploadStatus)
            MyBase.New
            Me.UploadFileResult = UploadFileResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AddPadsJobRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AddPadsJob", [Namespace]:="https://www.private.dacs.dla.mil", Order:=0)>  _
        Public Body As PadsUpload.AddPadsJobRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PadsUpload.AddPadsJobRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.private.dacs.dla.mil")>  _
    Partial Public Class AddPadsJobRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public recordToAdd As PadsUpload.PadsRecord
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal recordToAdd As PadsUpload.PadsRecord)
            MyBase.New
            Me.recordToAdd = recordToAdd
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AddPadsJobResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AddPadsJobResponse", [Namespace]:="https://www.private.dacs.dla.mil", Order:=0)>  _
        Public Body As PadsUpload.AddPadsJobResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PadsUpload.AddPadsJobResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.private.dacs.dla.mil")>  _
    Partial Public Class AddPadsJobResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public AddPadsJobResult As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AddPadsJobResult As Integer)
            MyBase.New
            Me.AddPadsJobResult = AddPadsJobResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface PADSUploadSoapChannel
        Inherits PadsUpload.PADSUploadSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PADSUploadSoapClient
        Inherits System.ServiceModel.ClientBase(Of PadsUpload.PADSUploadSoap)
        Implements PadsUpload.PADSUploadSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Online() As Boolean Implements PadsUpload.PADSUploadSoap.Online
            Return MyBase.Channel.Online
        End Function
        
        Public Function OnlineAsync() As System.Threading.Tasks.Task(Of Boolean) Implements PadsUpload.PADSUploadSoap.OnlineAsync
            Return MyBase.Channel.OnlineAsync
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PadsUpload_PADSUploadSoap_UploadFile(ByVal request As PadsUpload.UploadFileRequest) As PadsUpload.UploadFileResponse Implements PadsUpload.PADSUploadSoap.UploadFile
            Return MyBase.Channel.UploadFile(request)
        End Function
        
        Public Function UploadFile(ByVal Content() As Byte, ByVal FileName As String, ByVal IsEncrypted As Boolean) As PadsUpload.FileUploadStatus
            Dim inValue As PadsUpload.UploadFileRequest = New PadsUpload.UploadFileRequest()
            inValue.Body = New PadsUpload.UploadFileRequestBody()
            inValue.Body.Content = Content
            inValue.Body.FileName = FileName
            inValue.Body.IsEncrypted = IsEncrypted
            Dim retVal As PadsUpload.UploadFileResponse = CType(Me,PadsUpload.PADSUploadSoap).UploadFile(inValue)
            Return retVal.Body.UploadFileResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PadsUpload_PADSUploadSoap_UploadFileAsync(ByVal request As PadsUpload.UploadFileRequest) As System.Threading.Tasks.Task(Of PadsUpload.UploadFileResponse) Implements PadsUpload.PADSUploadSoap.UploadFileAsync
            Return MyBase.Channel.UploadFileAsync(request)
        End Function
        
        Public Function UploadFileAsync(ByVal Content() As Byte, ByVal FileName As String, ByVal IsEncrypted As Boolean) As System.Threading.Tasks.Task(Of PadsUpload.UploadFileResponse)
            Dim inValue As PadsUpload.UploadFileRequest = New PadsUpload.UploadFileRequest()
            inValue.Body = New PadsUpload.UploadFileRequestBody()
            inValue.Body.Content = Content
            inValue.Body.FileName = FileName
            inValue.Body.IsEncrypted = IsEncrypted
            Return CType(Me,PadsUpload.PADSUploadSoap).UploadFileAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PadsUpload_PADSUploadSoap_AddPadsJob(ByVal request As PadsUpload.AddPadsJobRequest) As PadsUpload.AddPadsJobResponse Implements PadsUpload.PADSUploadSoap.AddPadsJob
            Return MyBase.Channel.AddPadsJob(request)
        End Function
        
        Public Function AddPadsJob(ByVal recordToAdd As PadsUpload.PadsRecord) As Integer
            Dim inValue As PadsUpload.AddPadsJobRequest = New PadsUpload.AddPadsJobRequest()
            inValue.Body = New PadsUpload.AddPadsJobRequestBody()
            inValue.Body.recordToAdd = recordToAdd
            Dim retVal As PadsUpload.AddPadsJobResponse = CType(Me,PadsUpload.PADSUploadSoap).AddPadsJob(inValue)
            Return retVal.Body.AddPadsJobResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PadsUpload_PADSUploadSoap_AddPadsJobAsync(ByVal request As PadsUpload.AddPadsJobRequest) As System.Threading.Tasks.Task(Of PadsUpload.AddPadsJobResponse) Implements PadsUpload.PADSUploadSoap.AddPadsJobAsync
            Return MyBase.Channel.AddPadsJobAsync(request)
        End Function
        
        Public Function AddPadsJobAsync(ByVal recordToAdd As PadsUpload.PadsRecord) As System.Threading.Tasks.Task(Of PadsUpload.AddPadsJobResponse)
            Dim inValue As PadsUpload.AddPadsJobRequest = New PadsUpload.AddPadsJobRequest()
            inValue.Body = New PadsUpload.AddPadsJobRequestBody()
            inValue.Body.recordToAdd = recordToAdd
            Return CType(Me,PadsUpload.PADSUploadSoap).AddPadsJobAsync(inValue)
        End Function
    End Class
End Namespace
